services:
  db:
    image: postgres:18
    container_name: db_cursos
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cursos_db
    ports:
      - '5432:5432'
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
