services:
  db:
    image: postgres:15
    container_name: cursos_backend_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cursos_db
    ports:
      - "5432:5432"